### ISSUE TITLE
Maybe upgrade node-forge to 0.7.0

### ISSUE THREAD

**Issue by deathweaselx86** [ryanseys/google-p12-pem#8]
I'm indirectly using this package with `google-auth-library`. At present, it is unusable with webpack and babel [without hackery] because of this issue: https://github.com/digitalbazaar/forge/issues/198

They've addressed it in 0.7.0. I know you just upgraded it. Any chance you could update node-forge again?

**Comment by vietkungfu** [comment]
yeah ! It is relevant to this error [forge#357](https://github.com/digitalbazaar/forge/pull/357) too.

**Comment by ryanseys** [comment]
Fixed in https://github.com/ryanseys/google-p12-pem/releases/tag/v0.1.2 sorry for the delay!
